altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  35ea8b3d-1379-47d5-8c2a-27a5ddfef0a0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-18T15:43:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6ede7170-0ba6-4936-89f0-f8451cfc9d42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 032cb1e1-bfe0-483b-93a1-0283e29c7638
        userCondition: null
    thumbFieldKey: null
fs: siteAssetsFs
handle: logo
name: logo
sortOrder: 4
subpath: logo
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
